2019-11-19 01:21:46,365 - DEBUG - Smart alarm clock refreshed.
2019-11-19 01:21:46,393 - DEBUG - Starting new HTTPS connection (1): api.openweathermap.org:443
2019-11-19 01:21:46,505 - DEBUG - https://api.openweathermap.org:443 "GET /data/2.5/weather?q=exeter&appid=8bb8c8c3507631f11bb9599e7795a718&units=metric HTTP/1.1" 200 425
2019-11-19 01:21:46,517 - DEBUG - Starting new HTTPS connection (1): newsapi.org:443
2019-11-19 01:21:46,973 - DEBUG - https://newsapi.org:443 "GET /v2/top-headlines?country=gb&apiKey=86a97a39f14a4a1eac894868d7b9726c HTTP/1.1" 200 12675
2019-11-19 01:21:47,025 - INFO - 127.0.0.1 - - [19/Nov/2019 01:21:47] "GET / HTTP/1.1" 200 -
2019-11-19 01:22:09,427 - DEBUG - Smart alarm clock refreshed.
2019-11-19 01:22:09,447 - DEBUG - Starting new HTTPS connection (1): api.openweathermap.org:443
2019-11-19 01:22:09,562 - DEBUG - https://api.openweathermap.org:443 "GET /data/2.5/weather?q=exeter&appid=8bb8c8c3507631f11bb9599e7795a718&units=metric HTTP/1.1" 200 425
2019-11-19 01:22:09,590 - DEBUG - Starting new HTTPS connection (1): newsapi.org:443
2019-11-19 01:22:10,070 - DEBUG - https://newsapi.org:443 "GET /v2/top-headlines?country=gb&apiKey=86a97a39f14a4a1eac894868d7b9726c HTTP/1.1" 200 12675
2019-11-19 01:22:10,114 - INFO - 127.0.0.1 - - [19/Nov/2019 01:22:10] "GET /?alarm=2019-11-19T01%3A23&alarm_label=repeat+test&alarm_repeat=repeating HTTP/1.1" 200 -
2019-11-19 01:22:40,175 - DEBUG - Smart alarm clock refreshed.
2019-11-19 01:22:40,187 - DEBUG - Starting new HTTPS connection (1): api.openweathermap.org:443
2019-11-19 01:22:40,307 - DEBUG - https://api.openweathermap.org:443 "GET /data/2.5/weather?q=exeter&appid=8bb8c8c3507631f11bb9599e7795a718&units=metric HTTP/1.1" 200 425
2019-11-19 01:22:40,335 - DEBUG - Starting new HTTPS connection (1): newsapi.org:443
2019-11-19 01:22:40,842 - DEBUG - https://newsapi.org:443 "GET /v2/top-headlines?country=gb&apiKey=86a97a39f14a4a1eac894868d7b9726c HTTP/1.1" 200 12675
2019-11-19 01:22:40,854 - INFO - 127.0.0.1 - - [19/Nov/2019 01:22:40] "GET / HTTP/1.1" 200 -
2019-11-19 01:23:10,952 - DEBUG - Smart alarm clock refreshed.
2019-11-19 01:23:10,968 - DEBUG - Starting new HTTPS connection (1): api.openweathermap.org:443
2019-11-19 01:23:11,073 - DEBUG - https://api.openweathermap.org:443 "GET /data/2.5/weather?q=exeter&appid=8bb8c8c3507631f11bb9599e7795a718&units=metric HTTP/1.1" 200 425
2019-11-19 01:23:11,097 - DEBUG - Starting new HTTPS connection (1): newsapi.org:443
2019-11-19 01:23:11,573 - DEBUG - https://newsapi.org:443 "GET /v2/top-headlines?country=gb&apiKey=86a97a39f14a4a1eac894868d7b9726c HTTP/1.1" 200 12675
2019-11-19 01:23:11,641 - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\isaac\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pyttsx3\__init__.py", line 20, in init
    eng = _activeEngines[driverName]
  File "C:\Users\isaac\AppData\Local\Programs\Python\Python38-32\lib\weakref.py", line 131, in __getitem__
    o = self.data[key]()
KeyError: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\isaac\AppData\Local\Programs\Python\Python38-32\lib\site-packages\win32com\client\dynamic.py", line 89, in _GetGoodDispatch
    IDispatch = pythoncom.connect(IDispatch)
pywintypes.com_error: (-2147221008, 'CoInitialize has not been called.', None, None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\isaac\AppData\Local\Programs\Python\Python38-32\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\isaac\AppData\Local\Programs\Python\Python38-32\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\isaac\AppData\Local\Programs\Python\Python38-32\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\isaac\AppData\Local\Programs\Python\Python38-32\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\isaac\AppData\Local\Programs\Python\Python38-32\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\isaac\AppData\Local\Programs\Python\Python38-32\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\Users\isaac\OneDrive\Documents\University\Computer Science\Programming\Coursework\smart-alarm-clock\smart_alarm.py", line 51, in main
    get_alarm_inputs()
  File "c:\Users\isaac\OneDrive\Documents\University\Computer Science\Programming\Coursework\smart-alarm-clock\smart_alarm.py", line 250, in get_alarm_inputs
    alarm.run(blocking=False)
  File "C:\Users\isaac\AppData\Local\Programs\Python\Python38-32\lib\sched.py", line 151, in run
    action(*argument, **kwargs)
  File "c:\Users\isaac\OneDrive\Documents\University\Computer Science\Programming\Coursework\smart-alarm-clock\smart_alarm.py", line 321, in alert_alarm
    text_to_speech = pyttsx3.init()
  File "C:\Users\isaac\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pyttsx3\__init__.py", line 22, in init
    eng = Engine(driverName, debug)
  File "C:\Users\isaac\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pyttsx3\engine.py", line 30, in __init__
    self.proxy = driver.DriverProxy(weakref.proxy(self), driverName, debug)
  File "C:\Users\isaac\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pyttsx3\driver.py", line 52, in __init__
    self._driver = self._module.buildDriver(weakref.proxy(self))
  File "C:\Users\isaac\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pyttsx3\drivers\sapi5.py", line 23, in buildDriver
    return SAPI5Driver(proxy)
  File "C:\Users\isaac\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pyttsx3\drivers\sapi5.py", line 28, in __init__
    self._tts = win32com.client.Dispatch('SAPI.SPVoice')
  File "C:\Users\isaac\AppData\Local\Programs\Python\Python38-32\lib\site-packages\win32com\client\__init__.py", line 95, in Dispatch
    dispatch, userName = dynamic._GetGoodDispatchAndUserName(dispatch,userName,clsctx)
  File "C:\Users\isaac\AppData\Local\Programs\Python\Python38-32\lib\site-packages\win32com\client\dynamic.py", line 114, in _GetGoodDispatchAndUserName
    return (_GetGoodDispatch(IDispatch, clsctx), userName)
  File "C:\Users\isaac\AppData\Local\Programs\Python\Python38-32\lib\site-packages\win32com\client\dynamic.py", line 91, in _GetGoodDispatch
    IDispatch = pythoncom.CoCreateInstance(IDispatch, None, clsctx, pythoncom.IID_IDispatch)
pywintypes.com_error: (-2147221008, 'CoInitialize has not been called.', None, None)
2019-11-19 01:23:11,649 - INFO - 127.0.0.1 - - [19/Nov/2019 01:23:11] "GET / HTTP/1.1" 500 -
2019-11-19 01:23:16,873 - DEBUG - Smart alarm clock refreshed.
2019-11-19 01:23:16,901 - DEBUG - Starting new HTTPS connection (1): api.openweathermap.org:443
2019-11-19 01:23:16,999 - DEBUG - https://api.openweathermap.org:443 "GET /data/2.5/weather?q=exeter&appid=8bb8c8c3507631f11bb9599e7795a718&units=metric HTTP/1.1" 200 425
2019-11-19 01:23:17,031 - DEBUG - Starting new HTTPS connection (1): newsapi.org:443
2019-11-19 01:23:17,519 - DEBUG - https://newsapi.org:443 "GET /v2/top-headlines?country=gb&apiKey=86a97a39f14a4a1eac894868d7b9726c HTTP/1.1" 200 12675
2019-11-19 01:23:17,547 - INFO - 127.0.0.1 - - [19/Nov/2019 01:23:17] "GET / HTTP/1.1" 200 -
2019-11-19 01:23:40,795 - DEBUG - Smart alarm clock refreshed.
2019-11-19 01:23:40,807 - DEBUG - Starting new HTTPS connection (1): api.openweathermap.org:443
2019-11-19 01:23:40,929 - DEBUG - https://api.openweathermap.org:443 "GET /data/2.5/weather?q=exeter&appid=8bb8c8c3507631f11bb9599e7795a718&units=metric HTTP/1.1" 200 425
2019-11-19 01:23:40,960 - DEBUG - Starting new HTTPS connection (1): newsapi.org:443
2019-11-19 01:23:41,452 - DEBUG - https://newsapi.org:443 "GET /v2/top-headlines?country=gb&apiKey=86a97a39f14a4a1eac894868d7b9726c HTTP/1.1" 200 12675
2019-11-19 01:23:41,484 - INFO - 127.0.0.1 - - [19/Nov/2019 01:23:41] "GET /?alarm=2019-11-19T01%3A24&alarm_label=repeat+test&alarm_repeat=repeating HTTP/1.1" 200 -
2019-11-19 01:23:54,020 - DEBUG - Smart alarm clock refreshed.
2019-11-19 01:23:54,040 - DEBUG - Starting new HTTPS connection (1): api.openweathermap.org:443
2019-11-19 01:23:54,144 - DEBUG - https://api.openweathermap.org:443 "GET /data/2.5/weather?q=exeter&appid=8bb8c8c3507631f11bb9599e7795a718&units=metric HTTP/1.1" 200 425
2019-11-19 01:23:54,176 - DEBUG - Starting new HTTPS connection (1): newsapi.org:443
2019-11-19 01:23:54,676 - DEBUG - https://newsapi.org:443 "GET /v2/top-headlines?country=gb&apiKey=86a97a39f14a4a1eac894868d7b9726c HTTP/1.1" 200 12675
2019-11-19 01:23:54,704 - INFO - 127.0.0.1 - - [19/Nov/2019 01:23:54] "GET /?cancel_alarm=2019-11-19T01%3A23 HTTP/1.1" 200 -
2019-11-19 01:24:24,781 - DEBUG - Smart alarm clock refreshed.
2019-11-19 01:24:24,797 - DEBUG - Starting new HTTPS connection (1): api.openweathermap.org:443
2019-11-19 01:24:24,889 - DEBUG - https://api.openweathermap.org:443 "GET /data/2.5/weather?q=exeter&appid=8bb8c8c3507631f11bb9599e7795a718&units=metric HTTP/1.1" 200 425
2019-11-19 01:24:24,897 - DEBUG - Starting new HTTPS connection (1): newsapi.org:443
2019-11-19 01:24:25,361 - DEBUG - https://newsapi.org:443 "GET /v2/top-headlines?country=gb&apiKey=86a97a39f14a4a1eac894868d7b9726c HTTP/1.1" 200 12675
2019-11-19 01:24:25,369 - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\isaac\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pyttsx3\__init__.py", line 20, in init
    eng = _activeEngines[driverName]
  File "C:\Users\isaac\AppData\Local\Programs\Python\Python38-32\lib\weakref.py", line 131, in __getitem__
    o = self.data[key]()
KeyError: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\isaac\AppData\Local\Programs\Python\Python38-32\lib\site-packages\win32com\client\dynamic.py", line 89, in _GetGoodDispatch
    IDispatch = pythoncom.connect(IDispatch)
pywintypes.com_error: (-2147221008, 'CoInitialize has not been called.', None, None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\isaac\AppData\Local\Programs\Python\Python38-32\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\isaac\AppData\Local\Programs\Python\Python38-32\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\isaac\AppData\Local\Programs\Python\Python38-32\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\isaac\AppData\Local\Programs\Python\Python38-32\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\isaac\AppData\Local\Programs\Python\Python38-32\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\isaac\AppData\Local\Programs\Python\Python38-32\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\Users\isaac\OneDrive\Documents\University\Computer Science\Programming\Coursework\smart-alarm-clock\smart_alarm.py", line 51, in main
    get_alarm_inputs()
  File "c:\Users\isaac\OneDrive\Documents\University\Computer Science\Programming\Coursework\smart-alarm-clock\smart_alarm.py", line 250, in get_alarm_inputs
    alarm.run(blocking=False)
  File "C:\Users\isaac\AppData\Local\Programs\Python\Python38-32\lib\sched.py", line 151, in run
    action(*argument, **kwargs)
  File "c:\Users\isaac\OneDrive\Documents\University\Computer Science\Programming\Coursework\smart-alarm-clock\smart_alarm.py", line 321, in alert_alarm
    text_to_speech = pyttsx3.init()
  File "C:\Users\isaac\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pyttsx3\__init__.py", line 22, in init
    eng = Engine(driverName, debug)
  File "C:\Users\isaac\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pyttsx3\engine.py", line 30, in __init__
    self.proxy = driver.DriverProxy(weakref.proxy(self), driverName, debug)
  File "C:\Users\isaac\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pyttsx3\driver.py", line 52, in __init__
    self._driver = self._module.buildDriver(weakref.proxy(self))
  File "C:\Users\isaac\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pyttsx3\drivers\sapi5.py", line 23, in buildDriver
    return SAPI5Driver(proxy)
  File "C:\Users\isaac\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pyttsx3\drivers\sapi5.py", line 28, in __init__
    self._tts = win32com.client.Dispatch('SAPI.SPVoice')
  File "C:\Users\isaac\AppData\Local\Programs\Python\Python38-32\lib\site-packages\win32com\client\__init__.py", line 95, in Dispatch
    dispatch, userName = dynamic._GetGoodDispatchAndUserName(dispatch,userName,clsctx)
  File "C:\Users\isaac\AppData\Local\Programs\Python\Python38-32\lib\site-packages\win32com\client\dynamic.py", line 114, in _GetGoodDispatchAndUserName
    return (_GetGoodDispatch(IDispatch, clsctx), userName)
  File "C:\Users\isaac\AppData\Local\Programs\Python\Python38-32\lib\site-packages\win32com\client\dynamic.py", line 91, in _GetGoodDispatch
    IDispatch = pythoncom.CoCreateInstance(IDispatch, None, clsctx, pythoncom.IID_IDispatch)
pywintypes.com_error: (-2147221008, 'CoInitialize has not been called.', None, None)
2019-11-19 01:24:25,369 - INFO - 127.0.0.1 - - [19/Nov/2019 01:24:25] "GET / HTTP/1.1" 500 -
2019-11-19 01:24:40,597 - DEBUG - Smart alarm clock refreshed.
2019-11-19 01:24:40,605 - DEBUG - Starting new HTTPS connection (1): api.openweathermap.org:443
2019-11-19 01:24:40,701 - DEBUG - https://api.openweathermap.org:443 "GET /data/2.5/weather?q=exeter&appid=8bb8c8c3507631f11bb9599e7795a718&units=metric HTTP/1.1" 200 425
2019-11-19 01:24:40,709 - DEBUG - Starting new HTTPS connection (1): newsapi.org:443
2019-11-19 01:24:41,182 - DEBUG - https://newsapi.org:443 "GET /v2/top-headlines?country=gb&apiKey=86a97a39f14a4a1eac894868d7b9726c HTTP/1.1" 200 12675
2019-11-19 01:24:41,206 - INFO - 127.0.0.1 - - [19/Nov/2019 01:24:41] "GET / HTTP/1.1" 200 -
2019-11-19 01:24:56,925 - DEBUG - Smart alarm clock refreshed.
2019-11-19 01:24:56,945 - DEBUG - Starting new HTTPS connection (1): api.openweathermap.org:443
2019-11-19 01:24:57,057 - DEBUG - https://api.openweathermap.org:443 "GET /data/2.5/weather?q=exeter&appid=8bb8c8c3507631f11bb9599e7795a718&units=metric HTTP/1.1" 200 425
2019-11-19 01:24:57,069 - DEBUG - Starting new HTTPS connection (1): newsapi.org:443
2019-11-19 01:24:57,567 - DEBUG - https://newsapi.org:443 "GET /v2/top-headlines?country=gb&apiKey=86a97a39f14a4a1eac894868d7b9726c HTTP/1.1" 200 12675
2019-11-19 01:24:57,631 - INFO - 127.0.0.1 - - [19/Nov/2019 01:24:57] "GET / HTTP/1.1" 200 -
2019-11-19 01:25:10,648 - DEBUG - Smart alarm clock refreshed.
2019-11-19 01:25:10,664 - DEBUG - Starting new HTTPS connection (1): api.openweathermap.org:443
2019-11-19 01:25:10,762 - DEBUG - https://api.openweathermap.org:443 "GET /data/2.5/weather?q=exeter&appid=8bb8c8c3507631f11bb9599e7795a718&units=metric HTTP/1.1" 200 425
2019-11-19 01:25:10,794 - DEBUG - Starting new HTTPS connection (1): newsapi.org:443
2019-11-19 01:25:11,291 - DEBUG - https://newsapi.org:443 "GET /v2/top-headlines?country=gb&apiKey=86a97a39f14a4a1eac894868d7b9726c HTTP/1.1" 200 12675
2019-11-19 01:25:11,351 - INFO - 127.0.0.1 - - [19/Nov/2019 01:25:11] "GET /?alarm=2019-11-19T01%3A26&alarm_label=regular+test HTTP/1.1" 200 -
2019-11-19 01:25:41,418 - DEBUG - Smart alarm clock refreshed.
2019-11-19 01:25:41,430 - DEBUG - Starting new HTTPS connection (1): api.openweathermap.org:443
2019-11-19 01:25:41,546 - DEBUG - https://api.openweathermap.org:443 "GET /data/2.5/weather?q=exeter&appid=8bb8c8c3507631f11bb9599e7795a718&units=metric HTTP/1.1" 200 425
2019-11-19 01:25:41,574 - DEBUG - Starting new HTTPS connection (1): newsapi.org:443
2019-11-19 01:25:42,074 - DEBUG - https://newsapi.org:443 "GET /v2/top-headlines?country=gb&apiKey=86a97a39f14a4a1eac894868d7b9726c HTTP/1.1" 200 12675
2019-11-19 01:25:42,102 - INFO - 127.0.0.1 - - [19/Nov/2019 01:25:42] "GET / HTTP/1.1" 200 -
2019-11-19 01:26:12,179 - DEBUG - Smart alarm clock refreshed.
2019-11-19 01:26:12,191 - DEBUG - Starting new HTTPS connection (1): api.openweathermap.org:443
2019-11-19 01:26:12,295 - DEBUG - https://api.openweathermap.org:443 "GET /data/2.5/weather?q=exeter&appid=8bb8c8c3507631f11bb9599e7795a718&units=metric HTTP/1.1" 200 425
2019-11-19 01:26:12,323 - DEBUG - Starting new HTTPS connection (1): newsapi.org:443
2019-11-19 01:26:12,806 - DEBUG - https://newsapi.org:443 "GET /v2/top-headlines?country=gb&apiKey=86a97a39f14a4a1eac894868d7b9726c HTTP/1.1" 200 12675
2019-11-19 01:26:12,890 - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\isaac\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pyttsx3\__init__.py", line 20, in init
    eng = _activeEngines[driverName]
  File "C:\Users\isaac\AppData\Local\Programs\Python\Python38-32\lib\weakref.py", line 131, in __getitem__
    o = self.data[key]()
KeyError: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\isaac\AppData\Local\Programs\Python\Python38-32\lib\site-packages\win32com\client\dynamic.py", line 89, in _GetGoodDispatch
    IDispatch = pythoncom.connect(IDispatch)
pywintypes.com_error: (-2147221008, 'CoInitialize has not been called.', None, None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\isaac\AppData\Local\Programs\Python\Python38-32\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\isaac\AppData\Local\Programs\Python\Python38-32\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\isaac\AppData\Local\Programs\Python\Python38-32\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\isaac\AppData\Local\Programs\Python\Python38-32\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\isaac\AppData\Local\Programs\Python\Python38-32\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\isaac\AppData\Local\Programs\Python\Python38-32\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\Users\isaac\OneDrive\Documents\University\Computer Science\Programming\Coursework\smart-alarm-clock\smart_alarm.py", line 51, in main
    get_alarm_inputs()
  File "c:\Users\isaac\OneDrive\Documents\University\Computer Science\Programming\Coursework\smart-alarm-clock\smart_alarm.py", line 250, in get_alarm_inputs
    alarm.run(blocking=False)
  File "C:\Users\isaac\AppData\Local\Programs\Python\Python38-32\lib\sched.py", line 151, in run
    action(*argument, **kwargs)
  File "c:\Users\isaac\OneDrive\Documents\University\Computer Science\Programming\Coursework\smart-alarm-clock\smart_alarm.py", line 321, in alert_alarm
    text_to_speech = pyttsx3.init()
  File "C:\Users\isaac\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pyttsx3\__init__.py", line 22, in init
    eng = Engine(driverName, debug)
  File "C:\Users\isaac\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pyttsx3\engine.py", line 30, in __init__
    self.proxy = driver.DriverProxy(weakref.proxy(self), driverName, debug)
  File "C:\Users\isaac\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pyttsx3\driver.py", line 52, in __init__
    self._driver = self._module.buildDriver(weakref.proxy(self))
  File "C:\Users\isaac\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pyttsx3\drivers\sapi5.py", line 23, in buildDriver
    return SAPI5Driver(proxy)
  File "C:\Users\isaac\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pyttsx3\drivers\sapi5.py", line 28, in __init__
    self._tts = win32com.client.Dispatch('SAPI.SPVoice')
  File "C:\Users\isaac\AppData\Local\Programs\Python\Python38-32\lib\site-packages\win32com\client\__init__.py", line 95, in Dispatch
    dispatch, userName = dynamic._GetGoodDispatchAndUserName(dispatch,userName,clsctx)
  File "C:\Users\isaac\AppData\Local\Programs\Python\Python38-32\lib\site-packages\win32com\client\dynamic.py", line 114, in _GetGoodDispatchAndUserName
    return (_GetGoodDispatch(IDispatch, clsctx), userName)
  File "C:\Users\isaac\AppData\Local\Programs\Python\Python38-32\lib\site-packages\win32com\client\dynamic.py", line 91, in _GetGoodDispatch
    IDispatch = pythoncom.CoCreateInstance(IDispatch, None, clsctx, pythoncom.IID_IDispatch)
pywintypes.com_error: (-2147221008, 'CoInitialize has not been called.', None, None)
2019-11-19 01:26:12,898 - INFO - 127.0.0.1 - - [19/Nov/2019 01:26:12] "GET / HTTP/1.1" 500 -
2019-11-19 01:27:23,796 - DEBUG - Smart alarm clock refreshed.
2019-11-19 01:27:23,812 - DEBUG - Starting new HTTPS connection (1): api.openweathermap.org:443
2019-11-19 01:27:23,920 - DEBUG - https://api.openweathermap.org:443 "GET /data/2.5/weather?q=exeter&appid=8bb8c8c3507631f11bb9599e7795a718&units=metric HTTP/1.1" 200 425
2019-11-19 01:27:23,924 - DEBUG - Starting new HTTPS connection (1): newsapi.org:443
2019-11-19 01:27:24,400 - DEBUG - https://newsapi.org:443 "GET /v2/top-headlines?country=gb&apiKey=86a97a39f14a4a1eac894868d7b9726c HTTP/1.1" 200 12675
2019-11-19 01:27:24,432 - INFO - 127.0.0.1 - - [19/Nov/2019 01:27:24] "GET / HTTP/1.1" 200 -
2019-11-19 01:27:36,120 - DEBUG - Smart alarm clock refreshed.
2019-11-19 01:27:36,128 - DEBUG - Starting new HTTPS connection (1): api.openweathermap.org:443
2019-11-19 01:27:36,246 - DEBUG - https://api.openweathermap.org:443 "GET /data/2.5/weather?q=exeter&appid=8bb8c8c3507631f11bb9599e7795a718&units=metric HTTP/1.1" 200 425
2019-11-19 01:27:36,254 - DEBUG - Starting new HTTPS connection (1): newsapi.org:443
2019-11-19 01:27:36,721 - DEBUG - https://newsapi.org:443 "GET /v2/top-headlines?country=gb&apiKey=86a97a39f14a4a1eac894868d7b9726c HTTP/1.1" 200 12675
2019-11-19 01:27:36,741 - INFO - 127.0.0.1 - - [19/Nov/2019 01:27:36] "GET /?alarm=2019-11-19T01%3A28&alarm_label=repeat+test&alarm_repeat=repeating HTTP/1.1" 200 -
2019-11-19 01:28:06,805 - DEBUG - Smart alarm clock refreshed.
2019-11-19 01:28:06,809 - DEBUG - Starting new HTTPS connection (1): api.openweathermap.org:443
2019-11-19 01:28:06,917 - DEBUG - https://api.openweathermap.org:443 "GET /data/2.5/weather?q=exeter&appid=8bb8c8c3507631f11bb9599e7795a718&units=metric HTTP/1.1" 200 425
2019-11-19 01:28:06,929 - DEBUG - Starting new HTTPS connection (1): newsapi.org:443
2019-11-19 01:28:07,418 - DEBUG - https://newsapi.org:443 "GET /v2/top-headlines?country=gb&apiKey=86a97a39f14a4a1eac894868d7b9726c HTTP/1.1" 200 12675
2019-11-19 01:28:11,409 - INFO - 127.0.0.1 - - [19/Nov/2019 01:28:11] "GET / HTTP/1.1" 200 -
2019-11-19 01:28:24,810 - INFO -  * Detected change in 'C:\\Users\\isaac\\OneDrive\\Documents\\University\\Computer Science\\Programming\\Coursework\\smart-alarm-clock\\smart_alarm.py', reloading
2019-11-19 01:28:32,799 - DEBUG - Smart alarm clock refreshed.
2019-11-19 01:28:32,815 - DEBUG - Starting new HTTPS connection (1): api.openweathermap.org:443
2019-11-19 01:28:32,945 - DEBUG - https://api.openweathermap.org:443 "GET /data/2.5/weather?q=exeter&appid=8bb8c8c3507631f11bb9599e7795a718&units=metric HTTP/1.1" 200 425
2019-11-19 01:28:32,993 - DEBUG - Starting new HTTPS connection (1): newsapi.org:443
2019-11-19 01:28:33,505 - DEBUG - https://newsapi.org:443 "GET /v2/top-headlines?country=gb&apiKey=86a97a39f14a4a1eac894868d7b9726c HTTP/1.1" 200 12675
2019-11-19 01:28:33,641 - INFO - 127.0.0.1 - - [19/Nov/2019 01:28:33] "GET / HTTP/1.1" 200 -
2019-11-19 01:28:46,677 - DEBUG - Smart alarm clock refreshed.
2019-11-19 01:28:46,689 - DEBUG - Starting new HTTPS connection (1): api.openweathermap.org:443
2019-11-19 01:28:46,787 - DEBUG - https://api.openweathermap.org:443 "GET /data/2.5/weather?q=exeter&appid=8bb8c8c3507631f11bb9599e7795a718&units=metric HTTP/1.1" 200 425
2019-11-19 01:28:46,815 - DEBUG - Starting new HTTPS connection (1): newsapi.org:443
2019-11-19 01:28:47,287 - DEBUG - https://newsapi.org:443 "GET /v2/top-headlines?country=gb&apiKey=86a97a39f14a4a1eac894868d7b9726c HTTP/1.1" 200 12675
2019-11-19 01:28:47,331 - INFO - 127.0.0.1 - - [19/Nov/2019 01:28:47] "GET /?alarm=2019-11-19T01%3A29&alarm_label=repeat+test&alarm_repeat=repeating HTTP/1.1" 200 -
2019-11-19 01:29:17,417 - DEBUG - Smart alarm clock refreshed.
2019-11-19 01:29:17,453 - DEBUG - Starting new HTTPS connection (1): api.openweathermap.org:443
2019-11-19 01:29:17,554 - DEBUG - https://api.openweathermap.org:443 "GET /data/2.5/weather?q=exeter&appid=8bb8c8c3507631f11bb9599e7795a718&units=metric HTTP/1.1" 200 425
2019-11-19 01:29:17,574 - DEBUG - Starting new HTTPS connection (1): newsapi.org:443
2019-11-19 01:29:18,053 - DEBUG - https://newsapi.org:443 "GET /v2/top-headlines?country=gb&apiKey=86a97a39f14a4a1eac894868d7b9726c HTTP/1.1" 200 12675
2019-11-19 01:29:18,177 - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\isaac\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pyttsx3\__init__.py", line 20, in init
    eng = _activeEngines[driverName]
  File "C:\Users\isaac\AppData\Local\Programs\Python\Python38-32\lib\weakref.py", line 131, in __getitem__
    o = self.data[key]()
KeyError: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\isaac\AppData\Local\Programs\Python\Python38-32\lib\site-packages\win32com\client\dynamic.py", line 89, in _GetGoodDispatch
    IDispatch = pythoncom.connect(IDispatch)
pywintypes.com_error: (-2147221008, 'CoInitialize has not been called.', None, None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\isaac\AppData\Local\Programs\Python\Python38-32\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\isaac\AppData\Local\Programs\Python\Python38-32\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\isaac\AppData\Local\Programs\Python\Python38-32\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\isaac\AppData\Local\Programs\Python\Python38-32\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\isaac\AppData\Local\Programs\Python\Python38-32\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\isaac\AppData\Local\Programs\Python\Python38-32\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\Users\isaac\OneDrive\Documents\University\Computer Science\Programming\Coursework\smart-alarm-clock\smart_alarm.py", line 51, in main
    get_alarm_inputs()
  File "c:\Users\isaac\OneDrive\Documents\University\Computer Science\Programming\Coursework\smart-alarm-clock\smart_alarm.py", line 250, in get_alarm_inputs
    alarm.run(blocking=False)
  File "C:\Users\isaac\AppData\Local\Programs\Python\Python38-32\lib\sched.py", line 151, in run
    action(*argument, **kwargs)
  File "c:\Users\isaac\OneDrive\Documents\University\Computer Science\Programming\Coursework\smart-alarm-clock\smart_alarm.py", line 321, in alert_alarm
    text_to_speech = pyttsx3.init()
  File "C:\Users\isaac\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pyttsx3\__init__.py", line 22, in init
    eng = Engine(driverName, debug)
  File "C:\Users\isaac\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pyttsx3\engine.py", line 30, in __init__
    self.proxy = driver.DriverProxy(weakref.proxy(self), driverName, debug)
  File "C:\Users\isaac\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pyttsx3\driver.py", line 52, in __init__
    self._driver = self._module.buildDriver(weakref.proxy(self))
  File "C:\Users\isaac\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pyttsx3\drivers\sapi5.py", line 23, in buildDriver
    return SAPI5Driver(proxy)
  File "C:\Users\isaac\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pyttsx3\drivers\sapi5.py", line 28, in __init__
    self._tts = win32com.client.Dispatch('SAPI.SPVoice')
  File "C:\Users\isaac\AppData\Local\Programs\Python\Python38-32\lib\site-packages\win32com\client\__init__.py", line 95, in Dispatch
    dispatch, userName = dynamic._GetGoodDispatchAndUserName(dispatch,userName,clsctx)
  File "C:\Users\isaac\AppData\Local\Programs\Python\Python38-32\lib\site-packages\win32com\client\dynamic.py", line 114, in _GetGoodDispatchAndUserName
    return (_GetGoodDispatch(IDispatch, clsctx), userName)
  File "C:\Users\isaac\AppData\Local\Programs\Python\Python38-32\lib\site-packages\win32com\client\dynamic.py", line 91, in _GetGoodDispatch
    IDispatch = pythoncom.CoCreateInstance(IDispatch, None, clsctx, pythoncom.IID_IDispatch)
pywintypes.com_error: (-2147221008, 'CoInitialize has not been called.', None, None)
2019-11-19 01:29:18,185 - INFO - 127.0.0.1 - - [19/Nov/2019 01:29:18] "GET / HTTP/1.1" 500 -
